name: a basic workflow

on: push

jobs:
  job1:
    name: first job
    runs-on: ubuntu-latest
    steps:
      - name: step1 one
        uses: actions/checkout@v4
      - name: step two
        run: ls -la
      - run: pwd
  job2:
    name: step one of job2
    runs-on: windows:latest
    steps:
      - name: step one of job2
        uses: actions/checkout@v4
      - name: step two of job2
        run: pwd
